title: サンプルブログ
description: サンプルブログの詳細
baseurl: "blog-test"
url: "https://moraine8.github.io/"

timezone: Asia/Tokyo

markdown: kramdown

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed
